// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brtpdupsklezpkdnnvzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJydHBkdXBza2xlenBrZG5udnpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDcxMTksImV4cCI6MjA2MDQyMzExOX0.YwLjeBLUwPwpIesxci81VuIVKxn88duGuCPmfu8YbP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);